### PR TITLE
Feature/test1

### PR DESCRIPTION
**Pull request by realtingley**
### Description

A clear and concise summary of the change and which issue (if any) it fixes. Should also include relevant motivation and context.

Resolved or fixed issue: 

### Affirmation

- [ ] My code follows the [CONTRIBUTING.md](https://github.com/juice-shop/juice-shop/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by realtingley** [comment]
Apologies; errant git commands.

**Comment by bkimminich** [comment]
As this kind of accidental PR creation is happening several times per month, sometimes even per week, I'd be curious to how it happened in your case. Were you following some tutorial or demo and could point me to it? Maybe I can contact the author and help them refine it to avoid such accidents.

If it was just a mistake on your part, never mind either.

**Comment by realtingley** [comment]
GitHub's default behavior when creating a PR in a forked repo is to open it against the original (i.e.: not forked) repo. If you don't catch that...surprise!
Screenshot 2023-08-08 at 16 14 33

Edit: In my case, no tutorial or anything. Was using the repo to get familiar with a few code scanners.

**Comment by realtingley** [comment]
https://github.com/orgs/community/discussions/11729

**Comment by bkimminich** [comment]
Thanks for the link! 😀👍

**Pull request closed without merging**
