### PR TITLE
Add quantity labels

### PR DESCRIPTION
**Pull request by agrawalarpit14**
Show labels on products when quantity is less than 5 or if the
product is completely sold out.

Screenshot 2019-06-14 at 8 33 35 PM

### CODE REVIEW

**Comment by bkimminich** [comment]
Ooh, this looks really nice with the ribbons!

**Comment by agrawalarpit14** [comment]
> Ooh, this looks really nice with the ribbons!

Thanks😆, I will soon fix the tests and get it merge ready.

**Comment by bkimminich** [comment]
Ist it possible to use the warning and confirmation colors from each theme for the ribbons?

**Comment by agrawalarpit14** [comment]
> Ist it possible to use the warning and confirmation colors from each theme for the ribbons?

Screenshot 2019-06-15 at 8 37 44 AM

There you go!!😁😁
Please, let me know your feedback
Thank You!!✌🏻😁

**Comment by J12934** [comment]
Very fancy 👍
Unfortunately as by default all items are in pretty high stock its hard to get to the situation where the banners are displayed. 
How about we change the default to have a hand full of items in low / out of stock states?
Otherwise a lot of people might never see the fancy banners 😉

**Comment by bkimminich** [comment]
I already planned to do that for the artwork, melon bike and some other high tier items. Also something on first page.

**Comment by bkimminich** [comment]
Ah, just realized this would require a little refactoring where the quantity can be defined per product in the `.yml` config. If no quantity is specified, a random one could still be used.

**Comment by agrawalarpit14** [comment]
> Ah, just realized this would require a little refactoring where the quantity can be defined per product in the `.yml` config. If no quantity is specified, a random one could still be used.

Sure, I will soon open a fresh PR which takes care of this.😁😁

**Pull request merged**
