### PR TITLE
Add direct links for hacking instructor tutorials

### LINKED ISSUE #1331: Direct links to Hacking Instructor tutorials [🚀]
# :rocket: Feature request

### Description

It should be possible to directly jump to a hacking tutorial instead of having to go through the _Score Board_ and click the corresponding button. That way it would be easier to access from our own and third-party online documentation.

### Solution ideas

Define a sub-route or parameter of the _Score Board_ that virtually clicks the right tutorial button

### Possible alternatives

Define a completely new route like `/#/hacking-instructor/<tutorial-name>`

### PR DESCRIPTION
**Pull request by Scar26**
Fixes: #1331 

Hacking Instructor tutorials can now be directly accessed via `/#/hacking-instructor/{{challenge.name}}`

linkdemo

### CODE REVIEW

**Comment by bkimminich** [comment]
Is it possible to build this in the way mentioned [here](https://github.com/bkimminich/juice-shop/issues/1331#issuecomment-597202473) so that the _Score Board_ is not spoilered by every such link?

**Comment by Scar26** [comment]
Should I make a new component or link it to the home page one then?

**Comment by bkimminich** [comment]
Jumping to the home route when using a tutorial link seems like the easiest approach, I would think.

**Comment by Scar26** [comment]
Done
Also, changed the challenge variable to a query parameter. This prevents multiple tutorials from being started at the same time.

So instructors are now accessible via `/#/hacking-instructor?challenge={{challenge.name}}`

**Comment by Scar26** [comment]
Not sure why the login api test is failing... it's working on local. Does this have something to do with the CSP injection challenge? Because I didn't actually change anything that could affect login in this PR

**Comment by bkimminich** [comment]
That login test with the accountant user on of those frequently failing due to #1309. It's annoying, but all is good on your end here! I've added already a nice (generated) table to the official website with links to all tutorials:

image

(https://owasp.org/www-project-juice-shop/#div-challenges)

**Comment by Scar26** [comment]
Cool!

**Pull request merged**
