### PR TITLE
app.routing.ts: Making use of isAdmin

### PR DESCRIPTION
**Pull request by agrawalarpit14**
Enforcing isAdmin is true to route to
/#/administration

Part of #336

### CODE REVIEW

**Comment by agrawalarpit14** [comment]
The flow of the challenge can be seen [here](https://drive.google.com/file/d/1kbMarFSUTLFgZPNBN_c7TjeVQKkJICLf/view?usp=sharing). 
Hi @bkimminich Please let me know if you want any changes to be done and if I can start to write tests?

**Comment by bkimminich** [comment]
Looks good to me, but I think other than making the "Admin Section" challenge :star::star: instead of :star: there's no additional new challenge to be made out of this, because there's already multiple ways to elevate privileges to get to the Admin page.

**Comment by bkimminich** [comment]
~We could instead make this a new challenge "JWT Tier 0.5" (:star::star::star:) with description something like _"Become an admin temporarily. (Do not log in as an actual admin user)"_ ... To verify we could check if the JWT has `isAdmin=true` but the mentioned user account is not really an admin in the `Users` table.~

**Comment by agrawalarpit14** [comment]
Hi @bkimminich It sounds great. Then I will go on building the challenge "JWT Tier 0.5" and about this if there is no change can I start writing the tests(solving it in a way where user uses an admin account) ?🤩

**Comment by bkimminich** [comment]
Ah, sorry, I just re-watched your video in better resolution and saw that you actually used the same attack needed for "JWT Tier 1" to manipulate the admin flag in the token. So, no new challenge here, I guess... I'll merge your change as is and just increase difficulty for "Admin Access" challenge by 1. Thanks a lot for adding a first step of role-based authorization via JWT to the Juice Shop! :+1:

**Pull request merged**
