### PR TITLE
Implementation of multiple user types

### PR DESCRIPTION
**Pull request by agrawalarpit14**
In the current implementation:
- isAdmin(boolean) --> userType(integer)
- Only four kinds of users are accepted.[0: customer, 1: prime, 2: accounting, 3: admin]

### CODE REVIEW

**Comment by J12934** [comment]
I'm personally not a big fan of representing user types as integers.
Sure thats memory efficient, but not at all readable, which is way more important to me.

I'd prefer to make this a string field with `customer`, `prime`, `accounting` & `admin` as the only accepted values.

**Comment by bkimminich** [comment]
I was thinking if maybe combining permissions by adding the int values would become a really reaaaally stupid auth challenge at some point, like having ambiguous sums leading you to a free prime subscription or admins role... But maybe that a bit too far fetched even for the Juice Shop.

I'd be fine with fixed string list as well.

**Comment by agrawalarpit14** [comment]
Sure @J12934 and @bkimminich. I will go forward with the strings and soon update the PR.

**Comment by agrawalarpit14** [comment]
Hi @J12934 and @bkimminich. Please let me know if the implementation looks fine now.
Thank You!! very much 😁😁😁😆

**Review by J12934 — APPROVED** [review]

**Comment by bkimminich** [comment]
I'd still recommend to use something like `user.userType === insecurity.roles.admin` over `=== 'admin'` everywhere. Not that it makes a huge difference, but it prevents problems from typos and makes sure only actually existing roles are used.

**Comment by agrawalarpit14** [comment]
Hi @bkimminich, I have updated the PR, taking your review into account . Please let me know your feedback.
Thank You😁😁✌🏻😆

**Comment by bkimminich** [comment]
Code looks good to me, the only small change I'd recommend is renaming `userType` into just `role` for clarity and consistency. :+1:

**Comment by agrawalarpit14** [comment]
> Code looks good to me, the only small change I'd recommend is renaming `userType` into just `role` for clarity and consistency. 👍

Sure, I will do it right away.😁

**Pull request merged**
