### PR TITLE
Update angular.json for new node_modules/flag-icons

### PR DESCRIPTION
**Pull request by RobertoBorges**
### Description

Flags Icons changed and the old css icons is breaking the build since some icons don't exists anymore.

Resolved or fixed issue: 

The old Icons CSS have references to ea.* files that don't exist anymore.

304.5 ./node_modules/flag-icons/sass/flag-icons.scss - Error: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
304.5 /juice-shop/frontend/node_modules/flag-icons/sass/flag-icons.scss:1800:25: Can't resolve '../flags/4x3/ea.svg' in '/juice-shop/frontend/node_modules/flag-icons/sass'
304.5
304.5 ./node_modules/flag-icons/sass/flag-icons.scss - Error: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
304.5 /juice-shop/frontend/node_modules/flag-icons/sass/flag-icons.scss:1803:25: Can't resolve '../flags/1x1/ea.svg' in '/juice-shop/frontend/node_modules/flag-icons/sass'
304.5
304.5
304.7 npm ERR! code 1
304.7 npm ERR! path /juice-shop
304.7 npm ERR! command failed
304.7 npm ERR! command sh -c cd frontend && npm install --legacy-peer-deps && cd .. && npm run build:frontend && (npm run --silent build:server || cd .)

### Affirmation

- [x] My code follows the [CONTRIBUTING.md](https://github.com/juice-shop/juice-shop/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by bkimminich** [comment]
Hi! How does flipping from SASS to CSS solve the underlying problem? Is this a recommended change from the Flags maintainer? I've temporarily pinned the Flags module to version 6.8 as this problem only came with 6.9. Also it is reported to the module maintainer, so we might get a fix. Otherwise going with 6.8 for the time being seems fine.

**Comment by RobertoBorges** [comment]
> Hi! How does flipping from SASS to CSS solve the underlying problem? Is this a recommended change from the Flags maintainer? I've temporarily pinned the Flags module to version 6.8 as this problem only came with 6.9. Also it is reported to the module maintainer, so we might get a fix. Otherwise going with 6.8 for the time being seems fine.

Exactly, the maintainer left a message explaining that, if you look to the repo used by both, they use the same.... but old don't receive updates anymore:

https://www.npmjs.com/package/flag-icon-css

**Comment by bkimminich** [comment]
Alright, I bumped the version up to latest flag-icons release and will merge this if the CI/CD passed. Thanks for the fix!

**Comment by bkimminich** [comment]
@RobertoBorges, I forgot to ask you for your post address, so I can include you in the next batch of "thank you"-sticker packs for first-time contributors! You can reach me via Slack, Matrix or Email - all contact info you find on https://owasp-juice.shop!

**Pull request merged**
