### PR TITLE
score-board: Add class for overlay

### LINKED ISSUE #816: Score Board: Overlay while loading
When the score-board is loading, the overlay doesn't cover the whole page. It's just covers the size of screen. It can be visualised by scrolling when the page is loading.

### PR DESCRIPTION
**Pull request by agrawalarpit14**
The overlay will cover the whole page. With
spinner in the middle always.

Closes #816

### CODE REVIEW

**Comment by bkimminich** [comment]
Can you please attach a screenshot and short explanation of the intent of this change? Thank you!

**Comment by agrawalarpit14** [comment]
> Can you please attach a screenshot and short explanation of the intent of this change? Thank you!

Sure, I will do it right away.

**Comment by agrawalarpit14** [comment]
When the score-board is loading if the user scroll downwards. It looks like the following:

screenshot 2019-02-20 at 11 01 36 pm

After the change, when the user scrolls it will look like the following, i.e, it will cover the whole page.

screenshot 2019-02-20 at 11 07 21 pm

**Comment by bkimminich** [comment]
Aaaaaah, that's cool! Thanks! Looks like a bug in that [ngx-spinner](https://www.npmjs.com/package/ngx-spinner) module, maybe you want to PR this to them as a fix as well?

**Comment by bkimminich** [comment]
@agrawalarpit14, please email or Gitter-PM me your post address so I can send you our official 1st-time-contributor package!

**Comment by agrawalarpit14** [comment]
> Aaaaaah, that's cool! Thanks! Looks like a bug in that [ngx-spinner](https://www.npmjs.com/package/ngx-spinner) module, maybe you want to PR this to them as a fix as well?

Sure, I will see there repository. Thank You for informing.

**Pull request merged**
