### PR TITLE
Migration to Angular 15

### LINKED ISSUE #1925: [🏗️] Migration to Angular 15
<https://update.angular.io/?l=3&v=14.0-15.0>

### PR DESCRIPTION
**Pull request by Freedisch**
### Description

I just migrated the project from Angular 14.v to Angular 15.v by following the required steps 
https://update.angular.io/?l=3&v=14.0-15.0

image

Fixed issue: `#1925`

### Affirmation

- [x] My code follows the [CONTRIBUTING.md](https://github.com/juice-shop/juice-shop/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by bkimminich** [comment]
Please check the CI/CD results and compare with your local installation, test run results and server start logs. Doesn't seem to even resolve all specified dependencies right now.

**Comment by Freedisch** [comment]
I think there might have been some errors with some dependencies during the installation. Some package are not working with the updated version of typescript. I will check it  out

**Comment by Freedisch** [comment]
@bkimminich I have done some modifications and reinstalled some packages.

**Comment by Freedisch** [comment]
It seems that I still have some check failing 🥲

**Comment by bkimminich** [comment]
👏 Looks like we have a working version! I'll test that locally to see if the UI layout took any unexpected damage not caught by any test, especially the 3rd-party Angular components (e.g. code editor in Coding Challenges).

**Comment by bkimminich** [comment]
I did a quick smoke test and everything looks fine! I repaired the loading spinner on the Score Board, which was broken before already, but now it's using the Angular 15 component version and works again. Didn't notice any other UI issues:

✅    "ng-mat-search-bar": "^12.0.1",
✅     "ng-simple-slideshow": "^1.3.0-beta.11",
✅    "ng2-file-upload": "^1.4.0",
✅    "ngx-clipboard": "^15.1.0",
✅    "ngx-cookie": "^6.0.0",
✅    "ngx-highlightjs": "^6.1.2",
✅    "ngx-spinner": "^15.0.1",
✅    "ngx-text-diff": "^0.6.0",
❓     "ngx-window-token": "^6.0.0", (seems not used in the code currently)

**Comment by bkimminich** [comment]
@Freedisch, please send me an email or Gitter DM or Slack DM with your post address, so that I can send you our official "Thank you for your first PR!" sticker pack!

**Pull request merged**
