### PR TITLE
Explain that purchase limit includes previous orders

### PR DESCRIPTION
**Pull request by cnotin**
As an admin, I did not understand at first why I could not add one more "apple juice" in my basket (2 -> 3) since it was under the limit of 5 items, until I saw it counted the previous orders and check the orders history

Only German was translated for this message, so I translated the additional text with Google Translate and I let you check :)

### CODE REVIEW

**Comment by cnotin** [comment]
The Travis CI error looks strange, bug in code or in CI?

**Comment by bkimminich** [comment]
I'm not even sure it was ever supposed to count across all previous orders... That might just be a bug...

New strings are best just added in English to the corresponding `en.json` file and then we deal with translation on CrowdIn. Editing all JSON files kind of messes with that workflow and I'd have to do reinports on CrowdIn, so in the end it's often causing more work than helping to translate this way... 😬

**Comment by cnotin** [comment]
Do you prefer that I fix it by making it count only the number of items in the current basket?

Oh sorry I can remove the edits in translated versions!

**Comment by bkimminich** [comment]
👍 I think making the limit count per order is much more realistic and avoids confusion in general.

**Comment by cnotin** [comment]
Ok I'll do something like this

**Pull request closed without merging**
