### PR TITLE
Include GitLab Auto-Devops with additional scans

### PR DESCRIPTION
**Pull request by ricardoamarilla**
The SaaS and Dependency templates have changed in GitLab, this PR  includes the new format to call the templates and also include additional  security scans  such us: DAST, Container Scanning,  Secret Detection.

### CODE REVIEW

**Comment by bkimminich** [comment]
Thanks for this PR! As the old checks still run successfully, I never noticed that there's a newer template with more features! 👍

**Comment by bkimminich** [comment]
image

**Comment by bkimminich** [comment]
Fixed via https://github.com/bkimminich/juice-shop/commit/02ebda011dc3c96cee5f9bd824448fe59d3dfbc9

**Comment by bkimminich** [comment]
@ricardoamarilla, as a first-time contributor you're entitled to our famous sticker pack! All you need to do is sending me an email or Slack DM with your post address! 👍

**Comment by ricardoamarilla** [comment]
> @ricardoamarilla, as a first-time contributor you're entitled to our famous sticker pack! All you need to do is sending me an email or Slack DM with your post address! 👍

Nice! Glad to contribute, more to come!   I love this project!

**Pull request merged**
