### PR TITLE
feat(frontned): Update to v16

### PR DESCRIPTION
**Pull request by martinakraus**
### Description

This PR updates the Frontend to Angular 16. 
Following Libraries needed to be exchanged:

- ng-simple-slideshow -> ng-gallery was included which has even kind of the same API: https://www.npmjs.com/package/ng-gallery

- ngx-text-diff: -> https://github.com/ABenassi87/ngx-text-diff/issues/71
 A fork with an updated was included: @winarg/ngx-text-diff

- ng-mat-search-bar -> Custom Implementation

- anuglar-qrcode was exchanged with an updated ng-qrcode version -> to still be able to have the typo challenge this npm-package needs to be forked again qith a typo.

Resolved or fixed issue:  `#2173`

### Affirmation

- [X ] My code follows the [CONTRIBUTING.md](https://github.com/juice-shop/juice-shop/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by martinakraus** [comment]
Aaaand we are on v17 :) 
That wasn't luckily that hard.

**Comment by bkimminich** [comment]
Just fixed some linting issues, and now I'm running against a wall on Windows with one of the asset files being copied. I'll have to test if this happens in Angular 15 as well, or if it is a general issue with the file on Windows now:

```
> juice-shop@16.0.0 build:frontend
> cd frontend && node ./node_modules/@angular/cli/bin/ng build --output-hashing=none --vendor-chunk=true --source-map=false

√ Browser application bundle generation complete.
× Copying of assets failed.
Unable to copy assets: ENOENT: no such file or directory, copyfile 'C:\Data\GitHub\juice-shop\frontend\src\assets\public\images\
uploads\😼-#zatschi-#whoneedsfourlegs-1572600969477.jpg' -> 'C:\Data\GitHub\juice-shop\frontend\dist\frontend\assets\public\imag
es\uploads\😼-#zatschi-#whoneedsfourlegs-1572600969477.jpg'
npm ERR! code 1
npm ERR! path C:\Data\GitHub\juice-shop
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c cd frontend && npm install --legacy-peer-deps && cd .. && npm run build:fr
ontend && (npm run --silent build:server || cd .)
```

**Comment by bkimminich** [comment]
> Just fixed some linting issues, and now I'm running against a wall on Windows with one of the asset files being copied. I'll have to test if this happens in Angular 15 as well, or if it is a general issue with the file on Windows now:
> 
> ```
> > juice-shop@16.0.0 build:frontend
> > cd frontend && node ./node_modules/@angular/cli/bin/ng build --output-hashing=none --vendor-chunk=true --source-map=false
> 
> √ Browser application bundle generation complete.
> × Copying of assets failed.
> Unable to copy assets: ENOENT: no such file or directory, copyfile 'C:\Data\GitHub\juice-shop\frontend\src\assets\public\images\
> uploads\😼-#zatschi-#whoneedsfourlegs-1572600969477.jpg' -> 'C:\Data\GitHub\juice-shop\frontend\dist\frontend\assets\public\imag
> es\uploads\😼-#zatschi-#whoneedsfourlegs-1572600969477.jpg'
> npm ERR! code 1
> npm ERR! path C:\Data\GitHub\juice-shop
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c cd frontend && npm install --legacy-peer-deps && cd .. && npm run build:fr
> ontend && (npm run --silent build:server || cd .)
> ```

Ok, this problem is related to the Angular update somehow. It does not occur in the `develop` branch with Angular 15 when I build on Windows:

```
- Generating browser application bundles (phase: setup)...    TypeScript compiler options "target" and "useDefineForClassFie
lds" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browersli
st configuration. For more information, see https://angular.io/guide/build#configuring-browser-compatibility
    NOTE: You can set the "target" to "ES2022" in the project's tsconfig to remove this warning.
√ Browser application bundle generation complete.
√ Copying assets complete.
√ Index html generation complete.
```

Maybe Angular changed some library doing the copying of assets and the one being used now doesn't like the 🐱 in the filename - although Windows is totally fine with that.

**Comment by bkimminich** [comment]
Also, the Docker and smoke tests both fail from missing Angular CLI presumably at some point, e.g. in the Docker test pipeline: https://github.com/juice-shop/juice-shop/actions/runs/8006820248/job/21869440785#step:3:263

**Comment by bkimminich** [comment]
> Maybe Angular changed some library doing the copying of assets and the one being used now doesn't like the 🐱 in the filename - although Windows is totally fine with that.

I can confirm it is the emoji. Without it, copying works fine on Windows. @martinakraus, if you have an idea why this behavior might have changed, please try, but we can also fall back to removing the emoji. It is not crucial for the challenge around this image, for that only the `#` in the file name is relevant. It would be more fun to keep the emoji, of course, but not a deal-breaker for the Angular update.

I did some local testing, and the image slider and the search bar both worked fine for me! 🚀 I'll test the rest of the application later - might just not be able to do it before the weekend.

Really great work, @martinakraus! You might just have eliminated one of our GSoC project ideas in a couple days... 🤩

**Comment by bkimminich** [comment]
I changed the "🐱" in the filename into "ᓚᘏᗢ" for now and adapted all challenge checks and test cases accordingly. It shouldn't get in the way any more for the time being, and if it's possible to fix this, we can still revert [880801e](https://github.com/juice-shop/juice-shop/pull/2195/commits/880801ef6f02f50329a299f60baa61f0cc656e7e), because it's unrelated to your changes - except for the file itself the rest is all happening in the backend code.

**Comment by martinakraus** [comment]
Oh wow a lot to read. Thank you for the fast review.
But I didn't want to but stress on your end.  I'm sure there is a lot going on around you :)

I'll take a look as well on the issues you mentioned :)

Side note: Currently there is no "typo anuglar-qrcode" challenge any longer in this repo. The original repo angular-qrcode wasn't maintained any longer so I needed to take a complete different one.

Maybe in a calm moment you can also fork this one and name it to gn-qrcode or something :D

**Comment by bkimminich** [comment]
Yep, I'll do that - the challenge fix is super trivial luckily, as it's just checking for the lib name in a feedback comment.

**Comment by bkimminich** [comment]
The typosquatting target is now moved to another library. I picked one that had its last release 2 years ago, so it is less likely we will accidentally miss any updated on it... 😁

**Comment by martinakraus** [comment]
So one question what exactly is left to do?
I have finally some time again tomorrow to take a look at the emoji-issue.
But are there any other crucial issues left?

And thanks so so much for taking care of this 🙏🙏🙏

Maaaaaybe the next steps - could create other issues for that - we could go full standalone (with the new Angular standalone API) with the juicy shop and also updating material to v17 (which will be more struggling since it's css :D :D )

**Comment by bkimminich** [comment]
Hi! No need to thank me, we have to thank you for picking up this (for us) daunting issue! 🚀  I've merged your changes into https://github.com/juice-shop/juice-shop/tree/martinakraus-master already, so this PR can essentially be closed. I'm fixing some problems with linting and TypeScript errors currently, and also try to get the CI/CD back in sync with Angular 17 CLI. With some luck, now only some API tests fail, but those should be unrelated to your changes.

**Comment by bkimminich** [comment]
Already merged into https://github.com/juice-shop/juice-shop/tree/martinakraus-master

**Comment by bkimminich** [comment]
Does `Error: Could not find the '@angular-builders/custom-webpack:browser' builder's node package.` ring a bell for you? I don't spot what's wrong with that, as the module is listed in `package.json` and `angular.json`... 🤷 

https://github.com/juice-shop/juice-shop/actions/runs/8064002887/job/22026980110

**Comment by martinakraus** [comment]
Not really to be honest. 
So it appears by running `cd frontend && ng build --output-hashing=none --vendor-chunk=true --source-map=false`
I'm pretty sure that I did exactly that as well before but will try to reproduce this on my machine.
What's the node version running on build machines?

**Comment by bkimminich** [comment]
> Not really to be honest. So it appears by running `cd frontend && ng build --output-hashing=none --vendor-chunk=true --source-map=false` I'm pretty sure that I did exactly that as well before but will try to reproduce this on my machine. What's the node version running on build machines?

We're on Node.js 20 as the default during CI/CD right now.

**Comment by bkimminich** [comment]
Still struggling with the failing smoke/Docker tests, but the single remaining API test error is from an expected console log that seems to have gone overboard with the update. It's needed as a hint for a challenge. Here's where it was: https://github.com/juice-shop/juice-shop/blob/bc9cef1276578675beeb596898068ae37a6b57ff/frontend/src/app/change-password/change-password.component.ts#L37

**Comment by bkimminich** [comment]
> Still struggling with the failing smoke/Docker tests, but the single remaining API test error is from an expected console log that seems to have gone overboard with the update. It's needed as a hint for a challenge. Here's where it was:
> 
> https://github.com/juice-shop/juice-shop/blob/bc9cef1276578675beeb596898068ae37a6b57ff/frontend/src/app/change-password/change-password.component.ts#L37

To clarify, the log is still in the code (https://github.com/juice-shop/juice-shop/blob/martinakraus-master/frontend/src/app/change-password/change-password.component.ts#L37) it just seems to be missing or looking slightly different in the generated main.js.

**Comment by bkimminich** [comment]
> > Still struggling with the failing smoke/Docker tests, but the single remaining API test error is from an expected console log that seems to have gone overboard with the update. It's needed as a hint for a challenge. Here's where it was:
> > https://github.com/juice-shop/juice-shop/blob/bc9cef1276578675beeb596898068ae37a6b57ff/frontend/src/app/change-password/change-password.component.ts#L37
> 
> To clarify, the log is still in the code (https://github.com/juice-shop/juice-shop/blob/martinakraus-master/frontend/src/app/change-password/change-password.component.ts#L37) it just seems to be missing or looking slightly different in the generated main.js.

Solved this one, now really just the smoke/Docker test failures remain.

**Pull request closed without merging**
