### PR TITLE
Apply product quantity limit per user on a per-order basis

### PR DESCRIPTION
**Pull request by cnotin**
Before, all quantities from all prior purchases were counted in the quota stored in the purchaseQuantity model.
Now only the quantity in the current order is checked as discussed in PR #1528

No issue in `npm run lint` and `npm run frisby`

### CODE REVIEW

**Comment by cnotin** [comment]
GitHub CI/CD looks nice 👏 except perhaps a little bug in e2e?

**Comment by bkimminich** [comment]
It's work in progress, but it looks very promising. Even Docker builds work ready... Heroku and some notifications stuff and Travis-CI is obsolete for push/PR... 👍

**Comment by bkimminich** [comment]
Thanks for pinging our new build pipeline! 🥳

**Comment by cnotin** [comment]
I'm hypnotized by it... so I couldn't help not launching it!!

**Comment by cnotin** [comment]
Sweet :)

**Pull request merged**
