### PR TITLE
Order Confirmation Format

### PR DESCRIPTION
**Pull request by agrawalarpit14**
Minor changes in the order confirmation format, addition of date etc.

### CODE REVIEW

**Comment by agrawalarpit14** [comment]
Screenshot 2019-03-14 at 12 55 04 PM

Please let me know of modifications and suggestions. Thank You!!🙂

**Comment by bkimminich** [comment]
Woohoo, layout!!! 😀

**Comment by agrawalarpit14** [comment]
> Woohoo, layout!!! 😀

😆😆🙂🙂
Please let me know if I should commit changes in `package-lock.json` while opening a PR? and also I was wondering does `appveyor` need to queue old commits corresponding to a PR once it has been synchronised?

Thank You!!

**Comment by bkimminich** [comment]
I just turned off the AppVeyor webwook for PRs, as it doesn't run any tests anyway...

**Pull request merged**
