### PR TITLE
refactor(forms): adjustments based on feedback

### PR DESCRIPTION
**Pull request by MarcRler**
- h3 changed to h1 to enlarge login text.

- first version of the welcome banner in form of HTML and CSS. This was previously implemented as SVG, but was not customizable.  

- restructuring of the Sidenav. First the sub menu was removed before the top-level elements were grouped under the corresponding headers.

- customizing the English language file because new keywords were needed

### CODE REVIEW

**Comment by MarcRler** [comment]
Please don't merge into the facelift branch yet. Since I just found out that I still have to make some adjustments.

**Comment by bkimminich** [comment]
Okay, thanks for mentioning! Please ping me when ready for merge.

**Comment by MarcRler** [comment]
The minor styling problems should now be fixed. Further adjustments regarding the welcome banner cannot be excluded. In addition, the output of the search results has been adapted and revised.

**Comment by bkimminich** [comment]
Merging now... Should be on http://juice-shop-experimental.herokuapp.com in <1h... 😀

**Comment by MarcRler** [comment]
Awesome!!

**Pull request merged**
