### PR TITLE
[WIP] Migrate server-side code to TypeScript 

### PR DESCRIPTION
**Pull request by paseaf**
This PR closes https://github.com/bkimminich/juice-shop/issues/1573
### Changes
- Introduced TypeScript and necesary type packages on backend
- Renamed all code files except `lib/insecurity.js` from `.js` to `.ts` (`npm run frisby` fails after renaming `insecurity.js`)
- Augmented `npm install` process to transpile
- Changed `npm start` to run server from transpiled JavaScript code
- Changed `test:server` and `e2e` tests to run with `ts-node`
- Changed `frisby` tests to run with `ts-jest` 
- **Update path resolution for server-side code**
**New Policy:** When accessing static files, Always use relative paths starting from project root. This makes sure both `.ts` and compiled `.js` files always access the same static file.
**Example change**: https://github.com/bkimminich/juice-shop/commit/03fd40377ad2d32ac8f43a6d36ea6712bc54f8b9

### TODOs Before Merge
- [x] Update `npm run lint` to work for .ts files
- [x] Find a way to suppress TypeScript-related ESLint errors
- [x] Update `Gruntfile.js`
- [x] Update relevant CI/CD configs if there is any
- [x] Update other relevant config files if there is any

### Future Works

- Fix TypeScript warnings/errors
- Rename `lib/insecurity.js` to `lib/insecurity.ts` once it doesn't break `npm run frisby`

### CODE REVIEW

**Comment by paseaf** [comment]
Will rebase and solve the conflicts tomorrow

**Comment by paseaf** [comment]
`npm run frisby` failed on Node 10 with the following errors:
```
 FAIL  test/api/addressApiSpec.ts
  ● Test suite failed to run

    evalmachine.<anonymous>:1
    globalThis
    ^

    ReferenceError: globalThis is not defined

      at evalmachine.<anonymous>:1:1
      at setupWindow (node_modules/jsdom/lib/jsdom/browser/Window.js:51:55)
      at new Window (node_modules/jsdom/lib/jsdom/browser/Window.js:107:3)
      at exports.createWindow (node_modules/jsdom/lib/jsdom/browser/Window.js:38:10)
      at new JSDOM (node_modules/jsdom/lib/api.js:36:20)
```
Need to find a way to solve this problem (or wait for Node 10 being deprecated :D )

**Comment by bkimminich** [comment]
I planned to get rid of Node 10 anyway pretty soon, as its EOL in April or something. Can do it now just as well.

**Comment by paseaf** [comment]
Have checked `frisby`, `test:server`, `e2e` tests locally:
- passed on Windows with Node 14 
- passed on Ubuntu with Node 12 and 14
- failed on Ubuntu with Node 10

I think the next step is updating Gruntfile and other related config files.

It would be faster if someone more familiar with them could take over. (I haven't used them before), Or I could also work on them from the next Weekend.
What do you think? @bkimminich

**Comment by bkimminich** [comment]
I'll merge the PR into a separate branch off develop and we can take it from there step by step, ok?

**Comment by paseaf** [comment]
> I'll merge the PR into a separate branch off develop and we can take it from there step by step, ok?

Sounds good!

**Pull request merged**
