### PR TITLE
Make code-fix component remember settings

### PR DESCRIPTION
**Pull request by Coder-Manan**
### Description

The `format` (SideBySide / LineByLine) of the code fix area used to change back when we changed the fix.
Now the `format` stays same in a single session

Resolved or fixed issue: #1949 

### Affirmation

- [x] My code follows the [CONTRIBUTING.md](https://github.com/juice-shop/juice-shop/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by bkimminich** [comment]
👍 - Should we leave the PR open for the cookie persistance to be added as well?

**Comment by Coder-Manan** [comment]
I am okay with keeping it open as well as the other way round.
In case this one is closed, I will raise another PR for cookie persistence.

**Comment by Coder-Manan** [comment]
@bkimminich I just added the cookie persistence and its working good when working on the frontend (Angular) side (using `npm run serve` and going to `localhost:4200`) but the cookies are not getting set when I interact with the site at `localhost:3000`. Is this an issue or is this related to the project architecture?

**Comment by bkimminich** [comment]
This only happens in the develop mode where two ports are involved. If you run `npm install && npm start` it should work as expected, as then everything happens on port 3000 only.

**Comment by Coder-Manan** [comment]
Why is the `test CI/CD` check failing?

**Comment by bkimminich** [comment]
> Why is the `test CI/CD` check failing?

Did you check the build results? 😉 The component you changed now uses the cookie service, but as this hasn't been needed before, it's not initialized in the corresponding test case: https://github.com/juice-shop/juice-shop/actions/runs/4047434473/jobs/6961785235#step:6:6432

While that could be "fixed" by just initializing it in the test and then making sure it doesn't run into null pointers, the actual fix would be to add a proper test for the newly added functionality as well.

**Comment by Coder-Manan** [comment]
Ok... I'll need some time to write the test as I have not written one before

**Comment by Coder-Manan** [comment]
Just noticed that there are other frontend files also using the `CookieService` so do I have to write a new test?

**Comment by Coder-Manan** [comment]
The error in the failing test is that `TypeError: Cannot read properties of undefined (reading 'hasKey')`(in code-fixes-component.ts). But this shouldn't be happening because the modules are imported correctly and everything is working fine when running the application an any computer. What do you think might be causing the error @bkimminich ?

**Comment by bkimminich** [comment]
Hm, you're injecting the uninitialized `cookieService` variable as the `CookieService`, so it's `undefined` for sure. Take a look at `local-backup.service.spec.ts` for an example on how to use the cookie service in a test case.

**Comment by bkimminich** [comment]
Cool, CI passed, I'll take a look at this early next week. Do you also want to add the two other pieces - persisting the "Show only differences" checkbox and including the new cookie(s) in the local backup format - from #1949 into this PR?

**Comment by Coder-Manan** [comment]
I will add the browser cookies for `Show only differences` in this PR but I think it will be good if I open another PR for local cookies because otherwise this PR may become too big.

**Comment by bkimminich** [comment]
I've merged this as-is because I'm doing a bugfix release right now, and there was really no good reason not to include this already. Looking forward to the second part of course! 😁

Also, @Coder-Manan, please DM me your address on Slack or Gitter and I will put you onto my growing list of "First time contributors" to receive a little goodie bag with stickers!

**Comment by Coder-Manan** [comment]
@bkimminich I'll need some more time to review as to how to implement the cookies related to the `Show only differences` options. Simply setting the property of the component is not working and calling the function `hideMatchingLinesChanged` is leading to an error so I think this requires some more analysis

**Pull request merged**
