### PR TITLE
added authenticated user to navbar

### LINKED ISSUE #388: Feature request: Show authenticated user in UI
We use this application to demonstrate some of the web application vulnerabilities. During such demo's it would be of great help to have the currently authenticated user shown on the page. This makes it easier to follow some of the authentication bypasses for our spectators.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/49826033-feature-request-show-authenticated-user-in-ui?utm_campaign=plugin&utm_content=tracker%2F6283055&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F6283055&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by omerlh**
should close #388 
I have some issues with the `userService.whoAmI()` - it did not return user details some of the times. Could it be related to issues with local development?

### CODE REVIEW

**Comment by omerlh** [comment]
I am not sure why the build is failing - I did not add new libraries.
Also, the tests failed because of authentication issues - but I am not sure how it is related to my changes.

**Comment by bkimminich** [comment]
You violated the code styleguide. Running `npm test` locally before pushing a PR is a good practice... 😉

```
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /home/travis/build/bkimminich/juice-shop/app/js/controllers/NavbarController.js:4:27: Trailing spaces not allowed.
  /home/travis/build/bkimminich/juice-shop/app/js/controllers/NavbarController.js:35:9: Expected indentation of 6 spaces but found 8.
  /home/travis/build/bkimminich/juice-shop/app/js/controllers/NavbarController.js:36:7: Expected indentation of 4 spaces but found 6.
```

**Comment by omerlh** [comment]
Oh I'm sorry. Somehow missed that...
Now that I actually run the tests I've found out that I actually broke some, so I've fixed them and added tests for the new feature.
BTW I'm still not sure why NSP failed as I did not added new packages...

**Comment by bkimminich** [comment]
Reverted as it
🛑 contained an unwanted `hello:` message
🛑 squeezed the text between logo and application title
🛑 **does not update the user after logging in _unless you `F5` the browser_.** I was at that same point way back when trying #49

**Comment by omerlh** [comment]
To be honest - I saw the "hello" as a feature, though that it might look better. I'll remove it. This is how it looks like right now:
screen shot 2017-11-29 at 8 33 18

Did you mean that I should make the email text smaller?

Edit:
I've also fixed the update bug - all was required is to emit an event on user login/logout. I tried to add tests for it, but for some reason, it did not work. Do you have any experience with testing event emitter?

**Pull request merged**
