### PR TITLE
Submit forms by hitting enter #753

### PR DESCRIPTION
**Pull request by aaryan01**
#753 
Now you can submit the login form just by pressing enter after entering your email and password.

### CODE REVIEW

**Comment by bkimminich** [comment]
Looks great, could you just please run `npm i -g standard && standard --fix` on the code and push it again? Is there maybe a way to make this submit via keyup event reusable in all forms?

**Comment by aaryan01** [comment]
@bkimminich   Sure I'll do that! As of now I can think of only one solution, to store it in a different file and import it but that would be overkill. I'll work on a better way and get back to you asap.

**Comment by aaryan01** [comment]
@bkimminich I have fixed the linting issue. I have also thought of a way to reuse the keyup event. We can create a function having the event listener, export it from main.ts and call it wherever needed. Working on it.

**Comment by bkimminich** [comment]
Sounds great! I've merged the login solution and look forward to your follow-up PR! 👌

**Pull request merged**
