### PR TITLE
NoSQL challenges

### PR DESCRIPTION
**Pull request by J12934**
Hi,
finally found some time to work further on adding challenges for NoSQL attack vectors into JuiceShop. (See Issue #328)

I previously had a bunch of problems adding MongoDB into the JuiceShop as MongoDB Binaries don't run to well in alpine containers. 
But i just found out that there is a near feature complete port of MongoDB in pure Javascript. This make it easy to install on every operating system and also "supports" the native attack vectors.😉

I'd love some feedback about the challenges and the implementation details

### CODE REVIEW

**Comment by bkimminich** [comment]
Great, I'll check it out and give it a try tomorrow! One slight issue I noticed from the diff view already: The way the existing reviews are declared in `datacreator.,js` will probably not work for anything other than the `default.yml` config, or at least not in ones with completely rewritten product inventory, right?

We could fix this by just having pre-existing reviews for the only up to three products which are mandatory anyway, which are the ones with:
* `useForProductTamperingChallenge`
* `useForChristmasSpecialChallenge`
* `fileForRetrieveBlueprintChallenge`
All those flags could be on one product actually (which would be mean, but it should work) so there is essentially only one _guaranteed_ product in the inventory.

@J12934 @wurstbrot Any other ideas how to address this? We could add a `review` and `reviewer` attribute to the config YAML spec, but `reviewer` would need to refer to a user somehow then.

**Comment by bkimminich** [comment]
I'm trying to rebuild your PR commit on AppVeyor, because it seemed to fail from the issue with `phantomjs-prebuilt` (https://github.com/Medium/phantomjs/issues/735), although your `package.json` seemed to have the `2.1.14` and not the `~2` in it they build log showed

```
npm WARN juice-shop@5.0.0-SNAPSHOT requires a peer of phantomjs-prebuilt@~2 but none was installed.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv
```

> Edit: Didn't help... ... okay, but this is something than can be fixed post-merge.

**Comment by bkimminich** [comment]
Great challenges, just tried them out (with e2e-test cheating, obviously...) 👍
I like the way the solution is tested, especially for the sleepy one! I'll merge and try to figure out what is wrong with phantomjs then. On my local node v8.x all works fine.

@J12934, I'll give you collaborator access to the main repository, that way we can fix some glitches faster together, ok?

* [ ] Eliminate datacreator configuability issue (see original comment above)
* [ ] Refer to user emails in datacreator as `jim@' + config.get('application.domain')` to keep it working in customized setups
* [x] Analyze and fix phantomjs issue on node 6.x
* [x] Some inconsistent use of "comment" instead of "review" is left in code

**Comment by bkimminich** [comment]
PhantomJS magically works fine after merging. I love this kind of stuff... 🌈

**Comment by J12934** [comment]
Ok cool 👍
Yup didnt remember that products can be configured, but the solutions you proposed sound good. I'll take a closer look on which works best.

**Comment by J12934** [comment]
I removed some more usages of "comment" in the `NoSQL_Challenge_Improvments` branch, i think that should have been all of them.

Considering the configuration aspect, i think changing the config.yml to support something like this would be the best approach:
```yml
products:
  - name: "Apple Juice (1000ml)"
    price: 1.99
    description: "The all-time classic."
    image: "apple_juice.jpg"
    reviews:
      message: 'Review Text'
      author: 'admin@{{domain}}'
```
The `{{domain}}` part could then be replaced via regex (or something else 😉) during the datacreation stage. This would make the configuration flexible as domain specific emails and completely different emails could be specified.

This would require merging the mongodb specific datacreator into the default datacreator. Probably a good idea anyway. 😀 
Will take a look into doing so tomorrow

**Comment by bkimminich** [comment]
That's a good idea. I guess the domain part could be left out. Instead the username would be enough: `admin`, `jim`, `bender`, `ciso` or `support`. Those are the statically declared users that exists regardless of config. My Google-address is kind of a special case, so I would limit the list of allowed users for the config.yml to the above that use the application domain as email.

**Comment by bkimminich** [comment]
How about this?

```yml
products:
  - name: "Apple Juice (1000ml)"
    price: 1.99
    description: "The all-time classic."
    image: "apple_juice.jpg"
    reviews:
      - text: 'Review Text'
        author: 'admin' # Options: admin, jim, bender, ciso, support
```

**Comment by J12934** [comment]
Ok that would  make it easier 😅
Though it would also make it impossible to use a different than the configured one. For example the one for the OAuth2 challenges. But as Long as it isnt really requiried it would be a waste of time adding extra logic which isnt used.

Edit:
Reread your comment and noticed that you had already said this 😅👍

**Pull request merged**
