### PR TITLE
Facelift: various adjustments and improvements

### PR DESCRIPTION
**Pull request by MarcRler**
UserProfile:
 - Updating the Material Design Lite Version
 - Customize the style so that it looks appealing even on mobile devices
 - Adding a tooltip for the file upload to show what is possible

Privacy-Policy:
 - In order to give the text a structure, several styling adjustments and dividers were added. These should separate the individual sections more clearly from each other and make the area clearer

Forgot-Password: 
 - Minor styling adjustment
 - replace the icon with a permanent hint

Login:
 - Minor styling adjustment

Register:
 - Minor styling adjustment
 - replace the icon with a permanent hint

Two-Factor:
 - Minor styling adjustment
 - Adding aria labels 
 - Add a tooltip for the code
 - Customize the color of text boxes
 - Adding SnackBars to inform the user about the successful setup or removal of SnackBars
 - Bugfixing
 - Customizing the FormControls

Two-Factor-Enter:
 - Minor styling adjustment
 - Adding aria labels

Change-Password:
- Adding Aria Labels
- Adding notes for password length
- small styling changes

Contact: 
- redesign of the contact form
- Styling adjustments
- Adding Aria Labels
- Adaptation of various code parts to allow better error handling

Data-Export:
- Styling adjustments
- Adding Aria Labels
- Display a message if the CAPTCHA cannot be loaded
- minor restructurings

Last-Login-IP:
- Styling adjustments

Video:
- Styling adjustments

### CODE REVIEW

**Comment by MarcRler** [comment]
Please don't merge yet. I have noticed that I have forgotten something.

**Comment by MarcRler** [comment]
It's all here now. Accordingly, a merge can now be performed.

**Comment by bkimminich** [comment]
Hm, all seemed fine in the PR, but now some XSS alert is playing games during e2e testing... Any idea where this is coming from?

**Comment by MarcRler** [comment]
What do you mean with playing games? Where do the "problems" occur? When I run the tests locally, the usual suspects appear, but nothing with xss :/ .
 
The changes I have made affect both the HTML files and the TypeScript files. For the HTML files it was mainly adjustments in the layout or styling, for the TypeScript files I adapted validators in a few places and integrated the SnackBar service. Purely from the feeling I would localize the possible cause in the TS files.

**Comment by bkimminich** [comment]
One of the XSS alerts seems to be playing "hide and seek" with us again. This happens sometimes and can usually be fixed by extending some wait period between two actions... I'll try to reproduce this locally, so far I couldn't...

**Comment by MarcRler** [comment]
I see what you mean. If you can reproduce it, I can take care of it afterwards.

**Comment by bkimminich** [comment]
Last two builds were fine again on Travis-CI... 😂

**Pull request merged**
