### PR TITLE
Add address component

### PR DESCRIPTION
**Pull request by agrawalarpit14**
This PR is part of Payment Component and includes
-  Addition, edition and deletion of addresses of a user.
- Frontend routes for the same.

### CODE REVIEW

**Comment by agrawalarpit14** [comment]
Hi!! @bkimminich @J12934 , Please let me know your feedback on the PR.😁😀

**Comment by J12934** [comment]
One thing i don't really like about the address and the payment information pull request is that both add UI to first add and then select information. Both behave conceptually pretty similar but look completely different and are implemented pretty differently.

I think i would prefer to reuse the style of the payment information screen here instead of reinventing the wheel.

**Comment by bkimminich** [comment]
@agrawalarpit14, please let me know when you are done with your changes so I can review and merge this one, okay?

**Comment by agrawalarpit14** [comment]
Hi @bkimminich This PR is good to go, from my side.😁😁

**Pull request merged**
