### PR TITLE
Issue 854: Retrieve languages and translation coverage from server 

### PR DESCRIPTION
**Pull request by alejandrosaenz117**
#854 

This PR includes the creation of the new `/rest/languages` API endpoint.  This API endpoints retrieves the language from the folder `frontend/dist/frontend/assets/i18n/`, parses for the language, utilizes the array copied over from language.ts to map icons, and finally utilizes the `diff` library to calculate translation percentage when comparing each language file to the `en.json`.

However, the language files from the target folder do not completely match up with the language array so a couple of countries are missing flags.  

Lastly, the translation calculation was a bit confusing so please let me know if I am not on the right track.

Example response:
``` {
    "key": "ko_KR",
    "lang": "한국어",
    "icons": [
      "kr"
    ],
    "percentage": 75
  }

### CODE REVIEW

**Comment by bkimminich** [comment]
Great implementation first of all! Thanks a lot! 👍

> However, the language files from the target folder do not completely match up with the language array so a couple of countries are missing flags.

What do you mean by that? Which languages do not show flag icons now? About the percentage calculation I added two commits to use it instead of the static `isFlask` attribute.

**Comment by J12934** [comment]
This is great as an initial implementation 👍
But the endpoint is currently pretty slow, about 1500ms on my machine. 

I'm guessing the thing slowing it down the most is that it does all the file reads one after the other. Also gets slowed down because the english file gets read anew for every language. 

Some tings which should be done on this (doesn't have to be in this PR in my opinion): 

1. Add api tests for the language percentage calculation.
2. Cache english language file during calculation.
3. Cache percentage calculation, so it will only get calculated the first time the endpoint gets called, or on server start.
4. Optimize percentage calculation to perform multiple file reads at the same time.

**Comment by alejandrosaenz117** [comment]
> Great implementation first of all! Thanks a lot! 👍

Thank you!

> What do you mean by that? Which languages do not show flag icons now? About the percentage calculation I added two commits to use it instead of the static `isFlask` attribute.

As for you question, it looks like two languages, Catalan and tlhIngan, were not available in the language.ts exported array.  Therefore, they do not have any flag icons associated to them.  I may have missed them.

> This is great as an initial implementation 👍

Thank you!

> But the endpoint is currently pretty slow, about 1500ms on my machine.
> 
> I'm guessing the thing slowing it down the most is that it does all the file reads one after the other. Also gets slowed down because the english file gets read anew for every language.
> 
> Some tings which should be done on this (doesn't have to be in this PR in my opinion):
> 
> 1. Add api tests for the language percentage calculation.
> 2. Cache english language file during calculation.
> 3. Cache percentage calculation, so it will only get calculated the first time the endpoint gets called, or on server start.
> 4. Optimize percentage calculation to perform multiple file reads at the same time.

I went ahead and modified it so that it only reads the `en.json` file once.  Though, I do agree with each of your points.  I can make updates after the initial push.

**Comment by bkimminich** [comment]
Catalan actually doesn't have a flag in the CSS library we use, so that's okay. And the other language needs to be filtered out on the backend so it is not sent in the response. It's Klingon and finding its JSON file is a hacking challenge... 😊 ... Didn't think it through that this change would make this challenge trivially easy... 😁

**Comment by alejandrosaenz117** [comment]
I should have known 🥉 ....I'm more of a Battlestar Galactica fan myself.  

I added a conditional to the language endpoint to filter Klingon out of the response.  I also went ahead and rolled the cookieService functionality from `OnInit` to get the language from the cookie into the `getLanguage()` function.  Anything else I need to update on this PR?

**Comment by bkimminich** [comment]
I made two small adjustments, but otherwise it looks really good! :100:

**Comment by alejandrosaenz117** [comment]
Awesome!  Do I need to do anything about the failing e2e test?  Looks unrelated this implementation.

**Comment by bkimminich** [comment]
I'm looking into why this particular e2e is failing ... might be a performance thing. I threw out `diff` as it turned out to be overkill and as @J12934 wrote was a real performance killer. Simple key-by-key comparison of the JSON objects is much faster and gives the expected % results. Anyway, great job, @Whamo12! If you send me your post address I'll send a little swag pack your way!

**Comment by alejandrosaenz117** [comment]
That makes sense, I'll check out what you did later.  I'll DM you for the swag!

**Comment by bkimminich** [comment]
Failing e2e is fixed by adding a short wait time between a script execution and the next browser interaction. Thermometer indicating translation ratio is also implemented:
image

**Comment by alejandrosaenz117** [comment]
Looks great.  It might be a good idea to move the `iconMap` array into it's own file and add instructions on how to add new languages.

**Pull request merged**
