### PR TITLE
Timing attack challenge

### PR DESCRIPTION
**Pull request by shoebpate1**

### CODE REVIEW

**Comment by bkimminich** [comment]
Is this actually a new category or can we sort it into one of the existing? Also the hint is very revealing if we really consider it a 5/6-star difficulty?

**Comment by bkimminich** [comment]
Also please don't forget the countryMapping in `fbctf.yml`.

**Comment by shoebpate1** [comment]
@bkimminich Any better suggestion for hint ?

**Comment by bkimminich** [comment]
`fileWriteChallenge` was already mapped (Iran), now is twice.

**Comment by bkimminich** [comment]
I like the punctuality thing! How about "Punctuality is the politeness of kings"?

**Comment by shoebpate1** [comment]
Changed it @bkimminich

**Pull request merged**
