### PR TITLE
Addition of Image Based Captcha in Data Export Component

### PR DESCRIPTION
**Pull request by agrawalarpit14**
In this PR:
- `svg-captcha` is used for creating the CAPTCHA.
- The CAPTCHA is not shown on first submitted Recycling request
- If the user submits another Data Export Request within 5mins the CAPTCHA is shown.
- Presently the captcha is verified at the back end at the route `/rest/verify-image-captcha` which shall be modified to `data-export` route while implementing #582 (I have added comments at the back end route `/rest/verify-image-captcha` for the change that would need to be done. The route should work in a similar manner as `api/Feedbacks`).

Apr-02-2019 22-25-44

Hi @bkimminich @J12934 @CaptainFreak Please let me know of your views and suggestions. If the implementation look decent to you, I will go on to make tests.
Thank You!!

Part of #784

### CODE REVIEW

**Comment by bkimminich** [comment]
Csn you please ping me when the data export from #881 has been merged in, then I'll do the merge of this PR and close the other. Thanks!

**Comment by agrawalarpit14** [comment]
> Csn you please ping me when the data export from #881 has been merged in, then I'll do the merge of this PR and close the other. Thanks!

Sure @bkimminich. I will do right away, IMO it won't take much time(I just have to harvest the changes that are made inside the API call).

**Comment by agrawalarpit14** [comment]
Hi @bkimminich I had this query, while serving the file I am experiencing two issues that will needed to be addressed:
- Since the extension is `.json` the error `403 Error: Only .md and .pdf files are allowed!` appears. Is it fine if I allow serving of `.json` files?
- The file by default will get committed to `git` since it isn't ignoring the creation of the file. Should I add an entry in `.gitignore` corresponding to it?
_PS: the files are being stored on the route `/ftp/<file_name>`_

**Comment by bkimminich** [comment]
We could
1. send the JSON response directly
2. or write to a different folder
3. or we really have to open up the `/ftp` folder for that format

Maybe for the beginning 1. is the easiest workaround?

**Comment by agrawalarpit14** [comment]
- In the present implementation all the fields corresponding to `JSON`, `PDF`, `Excel` do the same job.

Screenshot 2019-04-04 at 9 18 51 PM

- The `JSON` data is being rendered in a new window.

Screenshot 2019-04-04 at 9 20 55 PM

- I have used @aaryan01's code inside the `/rest/data-export` route(@aaryan01 I did few changes to account for the errors in code, corresponding to the condition when the user didn't have any previous orders, Please review and let me know if it introduces any errors in your opinion).

Hi @bkimminich . Please let me know your views and suggestions.
Thank You!!🙂🙂

**Comment by bkimminich** [comment]
Looks good, I'll merge and fiddle with it a bit... The CAPTCHA is not making the same mistake of accepting "old" ones as the math CAPTCHA on _Contact Us_, does it? At the moment it is free of intentional vulns, right?

**Comment by agrawalarpit14** [comment]
> Looks good, I'll merge and fiddle with it a bit... The CAPTCHA is not making the same mistake of accepting "old" ones as the math CAPTCHA on _Contact Us_, does it? At the moment it is free of intentional vulns, right?

No actually, presently it has even more vulnerabilities in the sense that it can be bypassed easily and it stores previous values in a database similar to older CAPTCHA. 
Let me know if I should make changes?

**Comment by bkimminich** [comment]
I saw that when I played with it... 😀 ... But it's okay for now.

**Pull request merged**
