### PR TITLE
Web3 Code Sandbox

### PR DESCRIPTION
**Pull request by rishabhkeshan**
### Description

Added a Web3 Coding Sandbox as part of GSoC'23:

- Added a new route /web3-sandbox where users can go and work with contracts on the fly
- Added multiple compiler versions support with last stable releases of all versions till `0.8.21`
- Added a value param to send Ethers to the contract while deployment/invoking
- Added error logs for easy contract debugging
- Added 3 core smart contract functionalities:
    1. Compile Contracts
        - Compile contracts on the fly using the inbuilt code ide powered by Code Mirror.
    2. Deploy Contracts
        - Post compilation, users can deploy contracts in the Sandbox itself.
    3. Invoke Contracts
        - Easily invoke contract functions post deployment with multiple comma separated input values support.

### Affirmation

- [ ] My code follows the [CONTRIBUTING.md](https://github.com/juice-shop/juice-shop/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by ShubhamPalriwala** [comment]
Hey @rishabhkeshan, is this ready for review? So that we can review it and possibly get it merged as well

**Comment by rishabhkeshan** [comment]
> Hey @rishabhkeshan, is this ready for review? So that we can review it and possibly get it merged as well

Hey @ShubhamPalriwala have marked the PR ready for review, Please do have a look at the below challenge name for finding the sandbox, I have kept the hint similar to the lines of other hidden URL based challenges.

image

**Comment by bkimminich** [comment]
> > Hey @rishabhkeshan, is this ready for review? So that we can review it and possibly get it merged as well
> 
> Hey @ShubhamPalriwala have marked the PR ready for review, Please do have a look at the below challenge name for finding the sandbox, I have kept the hint similar to the lines of other hidden URL based challenges.
> 
> image

Challenge name and description look good! Could you check the merge conflicts please, then we're almost good to go, I guess.

**Comment by rishabhkeshan** [comment]
> > > Hey @rishabhkeshan, is this ready for review? So that we can review it and possibly get it merged as well
> > 
> > 
> > Hey @ShubhamPalriwala have marked the PR ready for review, Please do have a look at the below challenge name for finding the sandbox, I have kept the hint similar to the lines of other hidden URL based challenges.
> > image
> 
> Challenge name and description look good! Could you check the merge conflicts please, then we're almost good to go, I guess.

Sure, doing the same.
Also the warnings with the additional 3 libraries do not go away if I try to add it in the `allowedCommonJSDependencies`, I tried adding the 3 packages but that did not work, will it be possible for you to take a look at the same?

**Pull request merged**
