### PR TITLE
Fixed frisby test failures not getting caught

### PR DESCRIPTION
**Pull request by J12934**
I figured out why the frisby test were failing silently (in the cases where they failed).

The close method was trying to access the server via the "this" context to which the server hasn't been attached to for quite some time now. This must have slipped through some refactoring quite some time ago.

This lead to a broken if which always took the else branch.
This killed the jest process before it could exit itself with the non zero exit code.

### CODE REVIEW

**Comment by J12934** [comment]
Good new / Bad news:

- Good News: The Api tests are breaking the build
- Bad News: The Api tests are breaking the build

As far as i can see the failures are the same as they have been on the develop branch.
Cant really reproduce that on my local machine, i have all tests passing there except the `POST file type XML with Quadratic Blowup attack` test. Not really sure whats going wrong in CI... ☹️

**Comment by bkimminich** [comment]
That's _awesome_ that you found the issue! It seems the Quadratic Blowup test is running into the `Entity reference loop detected` threshold of our beloved `libxmljs` instead of going through... I'll try to reduce its size a bit to see what happens.

**Comment by bkimminich** [comment]
Ok, with slightly smaller blowup size, it passes on Travis-CI and still passes locally for me. Might have found the sweet spot finally. I'll merge and we'll see if there's any other tests behaving flaky.

**Comment by bkimminich** [comment]
Oookay, seems like the API tests are acting crazy on Travis-CI only... Locally all pass for me. Do you still get them passing locally either, @J12934 @wurstbrot? I consider turning them off for now on Travis-CI... 😕

**Comment by J12934** [comment]
Yup passing locally for me (in most cases...)
Some of the issues are:

Sometimes the tests pass but jest is unable to exit cleanly because there is still some code running.
Jest will just hang then. Without exiting:
```log
Test Suites: 25 passed, 25 total
Tests:       4 skipped, 237 passed, 241 total
Snapshots:   0 total
Time:        19.795s, estimated 24s
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

Another thing I've noticed (which might be related to the first issue) is that, I often get the Challenge Solved log output for the `NoSQL Injection Tier 3` logged out, after the Test report is printed.
```log
Test Suites: 25 passed, 25 total
Tests:       4 skipped, 237 passed, 241 total
Snapshots:   0 total
Time:        20.214s
Solved challenge NoSQL Injection Tier 3 (All your orders are belong to us!)

=============================== Coverage summary ===============================
Statements   : 87.14% ( 827/949 )
Branches     : 74.55% ( 451/605 )
Functions    : 80.09% ( 181/226 )
Lines        : 87.07% ( 808/928 )
```

**Pull request merged**
