### PR TITLE
Display error while registering with an email address that exists

### PR DESCRIPTION
**Pull request by aaryan01**
Solves #879 

Screenshot from 2019-03-19 14-51-08

Is this error message fine or is it too long?
@bkimminich @J12934 Suggestions?

### CODE REVIEW

**Comment by bkimminich** [comment]
How about not _always_ showing a static error text but extract the one from the server, capitalize the first letter and show that? I mean `email must be unique` and show it as _Email must be unique._

image

Would also be another nice negative example for error handling being inconsistently done in different ways in the application... :-D

**Comment by bkimminich** [comment]
Independent of that, the error styling should be consistent with the rest of the frontend and use the global CSS class `error` for that purpose. Defining your own `errorMessage` class in the component is a no-go, especially with static color and extra font style it will break theming.

**Comment by aaryan01** [comment]
@bkimminich I'll update it asap. Thanks for the suggestions :)

**Comment by bkimminich** [comment]
@aaryan01 can you please `git pull` and check locally if things still work? I used GitHub web editor to make some adjustments to your solution to bring it closer to existing error handling behavior on (almost all) other screens. Thanks!

**Comment by aaryan01** [comment]
@bkimminich It is working as expected. Thanks for your help :)

**Comment by aaryan01** [comment]
Error displayed
Screenshot from 2019-03-19 23-19-23
When I focus on a different field
Screenshot from 2019-03-19 23-19-29

**Pull request merged**
