### PR TITLE
Fixes for code consistency in tracking order

### PR DESCRIPTION
**Pull request by shoebpate1**

### CODE REVIEW

**Comment by shoebpate1** [comment]
CI tests are failing because of 
``` 
npm ERR! code E404
npm ERR! 404 Not Found: angular@https://registry.npmjs.org/angular/-/angular-1.6.10.tgz
```

**Comment by bkimminich** [comment]
I restarted the build and it worked. Seems like it was a network issue.

**Comment by wurstbrot** [comment]
Thank you @CaptainFreak. I see PullRequests as a suggestion to change the code. With the ability for others involved in the project to give their opinion.

Please link this PR to the corresponding issue, as I can not see the benefit of it right now. I am very open to clean code, but I need to get it explained why it is better in an other way for this case.

**Comment by wurstbrot** [comment]
In PR https://github.com/bkimminich/juice-shop/pull/567 @bkimminich asked for consistency in the naming, because somtimes orderNo and sometimes OrderId was used. I understand this PR now.

**Review by wurstbrot — APPROVED** [review]

**Pull request merged**
