### PR TITLE
Fix broken link to project logo in app.json

### PR DESCRIPTION
**Pull request by crcastle**
Looks like project structure was changed and link to project logo in `app.json` no longer worked. This fixes that!

### CODE REVIEW

**Comment by bkimminich** [comment]
Thank you! How did you notice this? I wasn't aware that this logo is even used anywhere.

**Comment by crcastle** [comment]
When you click the deploy to heroku button, a broken image was shown during the deplo process. That’s where I noticed it. 😀

**Comment by crcastle** [comment]
Hi @bkimminich 👋 do you know when this will get merged to `master`? I am planning on highlighting the "Deploy to Heroku" button in this repo in Heroku's March newsletter. The newsletter ships on Wednesday this week. Apologies for not catching this earlier. I saw that this was merged, but missed that it was merged to `develop` instead of `master` until now.

Going to the URL of the deploy button will show a broken image until this is merged to master (or the deploy button URL is updated to deploy from `develop`).

Deploy button URL: https://heroku.com/deploy?template=https://github.com/bkimminich/juice-shop/tree/master

What it looks like:
image

**Comment by crcastle** [comment]
Hi @bkimminich just checking in on this again. Can this commit be merged to `master`? The newsletter mentioning this goes out tomorrow.

**Comment by bkimminich** [comment]
I'll merge it to `master` in a moment! Wasn't aware what this was needed for... 😁

**Comment by bkimminich** [comment]
Done!
image

**Comment by crcastle** [comment]
Thanks so much @bkimminich !

**Pull request merged**
