### PR TITLE
Added a cancel button to tutorials

### PR DESCRIPTION
**Pull request by the-pro**
Added a cancel button to the tutorials

### CODE REVIEW

**Comment by bkimminich** [comment]
Hm, this is not really convincing visually...

image

I suppose an "X" in the top right corner like in the challenge notifications would look more natural and also avoid those line breaks making the speech bubble unnecessarily huge.

@J12934, any opinion from you as the original hacking instructor author and designer? 🤖

**Comment by the-pro** [comment]
Yes even i was thinking about replacing it with a cross button. The cancel button kind of looks foreign to the tutorial box. I would love to know your opinion on this @J12934

**Comment by J12934** [comment]
Yup that looks indeed a bit intrusive.
I was thinking of "hiding" it behind one of the material design "..." context menus, these look less intrusive and can give more context with labels when opened.

But that might be pretty hard to implement as the HackingInstructor boxes live outside of angular and don't have the angular material design libs. Not sure if there is some browser / html element which might help here 🤔

**Comment by the-pro** [comment]
I tried to put on a cross button and it looked like this:

Screenshot from 2021-03-19 13-01-31


But moving the hacking instructor into angular would be cool and would make it less diverse.

**Comment by bkimminich** [comment]
Looks good to me!

**Comment by the-pro** [comment]
I am not able to understand why is it not passing the tests

**Comment by bkimminich** [comment]
Don't worry, the tests failed some other reason. In a re-run everything passed! I'll merge tomorrow when I had a chance to test it locally.

**Comment by the-pro** [comment]
Oh i dint know we could re run the tests!

**Comment by bkimminich** [comment]
If you send me an email with your post address, @the-pro, I'll send you a couple stickers for your fist merged PR! 👍

**Comment by the-pro** [comment]
Done sir 😄

**Comment by bkimminich** [comment]
We gotta do a little bit of CSS magic still to have the "X" not spill over the speech bubble. Only noticed that on my phone actually...

**Comment by the-pro** [comment]
I increased the bottom property by 2px and i think it should work fine on all of the tutorials.

**Pull request merged**
