### PR TITLE
[🚧] other(Cards API): masking card number on server side

### LINKED ISSUE #1498: [⭐] storage of entire credit card numbers
# :star: Challenge idea

### Description

I notice that the Cards API returns the full credit card number, while the UI only shows the last digits

### Underlying vulnerabilities

* entire card storage -> PCI/DSS
* returning more info than what's displayed 

### Expected difficulty

| :heavy_check_mark: / :x: | Difficulty                           |
|:------------------------:|:-------------------------------------|
|       :heavy_check_mark:    | :star:                               |
|       :heavy_check_mark:    | :star::star:                         |
|        :heavy_check_mark:     | :star::star::star:                   |
|     :grey_question:      | :star::star::star::star:             |
|     :grey_question:      | :star::star::star::star::star:       |
|     :grey_question:      | :star::star::star::star::star::star: |

### Possible attack flow

SQL injection allows to dump credit card numbers (or other ways to obtain the DB content?) that could be reused for a purchase by the attacker 
I have no idea how to implement a challenge to show the fact that entire numbers are returned by the API while it's masked in the UI

### PR DESCRIPTION
**Pull request by PranjalAgni**
Added masking logic for card number on the server side itself, so providing just the required data to client

Close #1498

### CODE REVIEW

**Comment by bkimminich** [comment]
Could you add the same behavior also for the `getPaymentMethodById` function, please?

**Comment by bkimminich** [comment]
To fix the CI job, you need to rebase w/ `develop`, because I turned off two tests there that no longer work thanks to some content warning on PasteBin... 😁

**Comment by PranjalAgni** [comment]
Develop branch was 227 commits ahead of master. Do I need to cherry pick my changes

**Comment by PranjalAgni** [comment]
I think, I have wrongly done the rebase. Should I close this pull request and create a new one ?

**Comment by bkimminich** [comment]
Ah you opened the PR to master, yeah that's no good and I overlooked it, sorry. Best close this one and do the changes against develop instead. Wasn't that much, so I would recommend rinse repeat over 🍒 picking commits.

**Comment by PranjalAgni** [comment]
Sure I will make required changes in develop.

**Pull request closed without merging**
