### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by gorkavicente**

### CODE REVIEW

**Comment by gorkavicente** [comment]
Proposal for Spanish messages.

**Comment by bkimminich** [comment]
Awesome! But why did you close the PR immediately? 😵 Almost missed it... 😀

**Comment by gorkavicente** [comment]
I'have closed unintentionally :) I've opened again.

**Comment by bkimminich** [comment]
Just merged it! Huge GRACIAS! 🇪🇸 Send me an email or Twitter DM with your address and I'll mail some stickers your way!

**Pull request merged**
