### PR TITLE
Women's Day Offer Challenge

### LINKED ISSUE #847: Offer Expired Challenge: Based on Clock
The flow of the challenge is like this:
Name: Clock Manipulation Challenge
Description: Order products on offer that expired in 2017
Tasks to be done: It would need the user to manipulate the clock of their machine
Flow: User goes to twitter and finds out a tweet about the offer which gives them the `/#/offer/<festive>` route, but when they try to access it they are shown `the offer has expired` but when they manipulate the clock it works out for them. They are able to order few products for free on this route.
Bug: After the offer was expired, the route was never removed.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/71152778-offer-expired-challenge-based-on-clock?utm_campaign=plugin&utm_content=tracker%2F6283055&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F6283055&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by agrawalarpit14**
The flow of challenge is as follows:
- The user obtains the coupon code 'WMNSDY2019' either through the
twitter account or by guessing the coupon code(knowing the fact that
the offer was on Women's day of 2019).
- When the user tries to use the coupon code, it is errored saying
'Invalid coupon.'
- The user will then modify their system time to be that of the
Womens Day(08 March 2019), after this using the coupon code will give
the user a discount of 75%.
- The user will then checkout(complete the purchase) to solve the
challenge.
@bkimminich @J12934 @CaptainFreak 
Please let me know of suggestions and improvements. Thank You

Closes #847

### CODE REVIEW

**Comment by agrawalarpit14** [comment]
The flow of the challenge can be seen [here](https://drive.google.com/file/d/1cS_XEy2JrtraeAxTB7HRSkz_mJuNmbIu/view?usp=sharing).

**Comment by bkimminich** [comment]
@agrawalarpit14, I just  fixed the merge conflicts, please make sure you get them before working on my review comments, okay?

**Comment by agrawalarpit14** [comment]
> @agrawalarpit14, I just fixed the merge conflicts, please make sure you get them before working on my review comments, okay?

Sure, I will pull the changes.

**Comment by bkimminich** [comment]
Btw, I rephrased the challenge description and also increased the difficulty already in my conflict resolution commit.

**Comment by agrawalarpit14** [comment]
> Btw, I rephrased the challenge description and also increased the difficulty already in my conflict resolution commit.

The difficulty `4` makes it 👌. I will go on and correct the e2e tests. Please let me know your comments. 
Thank You

**Comment by agrawalarpit14** [comment]
Hi @bkimminich , I was trying to perform basic tasks for `deal of the day` challenge meanwhile this review. In the present form it looks like [this](https://drive.google.com/file/d/1Q4-PlKBNLZN8vpvv1Lk505XkC9gpCpJP/view?usp=sharing). 
I had this query:
By `deal of the day` did you mean the product should be changed every-day because in the present implementation there is only one extra product. Please let me know of your suggestions.
Thank You!!!

**Comment by bkimminich** [comment]
@agrawalarpit14, please don't mix any deal-of-the-day ideas into this PR. Let's wrap this one up before moving to the next topic, ok?

**Comment by agrawalarpit14** [comment]
> @agrawalarpit14, please don't mix any deal-of-the-day ideas into this PR. Let's wrap this one up before moving to the next topic, ok?

Sure. I will wait for it. Got little over-excited😛
Thank You

**Comment by bkimminich** [comment]
@agrawalarpit14, you'll ping me when this

> So, I could ignore the actual challenge with the time clock and just send campaignSuccess: true in the checkout request and the challenge will be solved, right? This is a bit too easy of a cheat. Maybe do a bit more trickery, like base64(campaignCode + '-' + clientDate) and send that as campaignToken to verify on the server side? That way the attacker can either go for the client clock approach or learn how this campaignToken works from the client JS code and craft a token manually.

is addressed and pushed, ok? Keeping PRs open for too long only leads to merge issues... Thanks!

**Comment by agrawalarpit14** [comment]
> @agrawalarpit14, you'll ping me when this
> 
> > So, I could ignore the actual challenge with the time clock and just send campaignSuccess: true in the checkout request and the challenge will be solved, right? This is a bit too easy of a cheat. Maybe do a bit more trickery, like base64(campaignCode + '-' + clientDate) and send that as campaignToken to verify on the server side? That way the attacker can either go for the client clock approach or learn how this campaignToken works from the client JS code and craft a token manually.
> 
> is addressed and pushed, ok? Keeping PRs open for too long only leads to merge issues... Thanks!

Hi @bkimminich I will work on this right away. But I am wondering why I wasn't able to read this till now. Like now even I can see your review comments as quote reply but I am unable to find where you first wrote this.
Really sorry for postponing and Thank You

**Comment by agrawalarpit14** [comment]
Hi @bkimminich I have pushed the changes corresponding to your comment(quote reply). But, unfortunately I am still unable to find where it was originally posted. Please let me know so that I don't repeat such a mistake again. Please let me know your suggestions on the latest changes too.
Thank You!!🙂

**Comment by bkimminich** [comment]
I used the _Review_ function of GitHub to put this remark inline ... it is in the comment history but also appeared in the _Files changed_ tab.

**Comment by agrawalarpit14** [comment]
Hi @bkimminich It's quite weird coz my _files changed_ tab also doesn't contain any reviews. It says:
```
Show changes since your last review- You haven’t reviewed this pull request yet
```
Please let me know if you find a fix to this. Presently the PR looks like this for me: 
debug_comments
Thank You!!

**Comment by bkimminich** [comment]
Hi, I went over the code for a final round and renamed/rephrased the challenge a bit to be less obvious. Also put it into different category.

Two last open items:
* Why did you introduce a distinct `campaignError` flag and not just reuse the existing error label from the regular coupons? Would make the code a bit cleaner.
* Also, it looks to me that a campaign coupon is now kind of mandatory on checkout. This is not good, as it spoilers the challenge too much. Please do not have it by default and instead check properly on the server side if it is present and only then evaluate it.

Please ping me when ready and I'll finally merge! Thanks a lot! 👍

**Comment by agrawalarpit14** [comment]
Hi @bkimminich I have made the changes requested by you. Please review.
Thank You!!!

**Comment by agrawalarpit14** [comment]
Hi @bkimminich I am really sorry I think now I understand what you really meant by second point in your review. Should I make this argument optional?

**Comment by agrawalarpit14** [comment]
Hi @bkimminich I have made the coupon optional. Please let me know if I anymore changes are needed. Really sorry for not carefully correcting it in one go.
Thank You!!

**Comment by bkimminich** [comment]
Don't worry! 😀 Looks good to me. Can't merge before tomorrow probably, just so you know. Thanks! 👍

**Comment by agrawalarpit14** [comment]
Thanks!!🙂🙂🙂🙂🙂🙂

**Pull request merged**
