### PR TITLE
updated socket.io and socket.io-client 

### PR DESCRIPTION
**Pull request by cigar-galaxy82**

### CODE REVIEW

**Comment by bkimminich** [comment]
I just checked out the PR branch locally. The tests run into the same problem on my Win10 machine than they do on GitHub CI:

```
> cd frontend && ng test --watch=false --source-map=true && cd .. && nyc --report-dir=./build/reports/coverage/server-tests mocha test/server

    'node-sass' usage is deprecated and will be removed in a future major version. To opt-out of the deprecated behaviour and start using 'sass' uninstall 'node-sass'.
'karma-coverage-istanbul-reporter' usage has been deprecated since version 11.
Please install 'karma-coverage' and update 'karma.conf.js.' For more info, see https://github.com/karma-runner/karma-coverage/blob/master/README.md
\ Generating browser application bundles (phase: building)...09 01 2021 11:15:25.534:INFO [karma-server]: Karma v5.1.1 server started at http://localhost:9876/
09 01 2021 11:15:25.539:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
09 01 2021 11:15:25.544:INFO [launcher]: Starting browser ChromeHeadless
√ Browser application bundle generation complete.
09 01 2021 11:16:25.548:WARN [launcher]: ChromeHeadless have not captured in 60000 ms, killing.
09 01 2021 11:16:25.725:INFO [launcher]: Trying to start ChromeHeadless again (1/2).
09 01 2021 11:17:25.736:WARN [launcher]: ChromeHeadless have not captured in 60000 ms, killing.
09 01 2021 11:17:25.770:INFO [launcher]: Trying to start ChromeHeadless again (2/2).
09 01 2021 11:18:25.782:WARN [launcher]: ChromeHeadless have not captured in 60000 ms, killing.
09 01 2021 11:18:25.908:ERROR [launcher]: ChromeHeadless failed 2 times (timeout). Giving up.
npm ERR! Test failed.  See above for more details.
```

**Comment by cigar-galaxy82** [comment]
Is there is particular reason causing the error?😢

**Comment by bkimminich** [comment]
Don't know, but as it only happens with the new Socket.io version I would say that it's the culprit here... 🙃

**Comment by cigar-galaxy82** [comment]
I checked this on my local ubuntu and all cases passed

**Comment by bkimminich** [comment]
Could you rebase your fork from `develop` and push again? That way you'll get the new retry/timeout configuration for most test steps. Unit and integration tests will be retried twice, end-to-end tests once in case they fail initially. That way we can at least see the final result for all the different OS/Node combinations on GitHub, because the first failing job will no longer kill the others which might still be running.

**Comment by bkimminich** [comment]
Closing due to unresolved test errors. Please open new PR after rebase of fork to test with CI/CD retries.

**Pull request closed without merging**
