### PR TITLE
Fix absolute paths for serveIndex plugin

### PR DESCRIPTION
**Pull request by JamesCullum**
Before: Running juiceshop ina subdirectory broke the links to files that are interacted with using the serve-index package (eg /ftp), as it uses an absolute link. From domain.com/subdir/ftp it will link to domain.com/ftp (which is not available).

Now: All links are rewritten to be relative, so that even if it runs in a subfolder it will continue to work.

There should be no impact for projects in the root directory.

Attribution goes again to Panasonic Information Systems Company Europe GmbH

### CODE REVIEW

**Comment by JamesCullum** [comment]
Travis CI test is stuck - maybe you can restart it or skip that test

**Comment by J12934** [comment]
> Travis CI test is stuck - maybe you can restart it or skip that test

Restarted the stuck build. Hopefully it behaves this time 😅

**Comment by JamesCullum** [comment]
That one Mac one doesn't want to run - I believe that's why there just was a maintenance of that environment.

**Comment by bkimminich** [comment]
There seem to be some general issues with OSX builds at the moment... In another build on `develop` these failed as well before even doing anything.

**Comment by bkimminich** [comment]
Mac builds seem to work again, I'm restarting the job for this PR: https://travis-ci.org/github/bkimminich/juice-shop/builds/665040311

**Comment by JamesCullum** [comment]
Or did it? :P

**Comment by bkimminich** [comment]
1 of 3 passed at least...

**Comment by JamesCullum** [comment]
Initial run 2/3 passed - do we know when the issue is fixed on their side?

**Comment by JamesCullum** [comment]
Can you try again?

**Comment by bkimminich** [comment]
Please rebase with `develop`, the unit tests are passing there again now.

**Comment by bkimminich** [comment]
Also I've found at least one additional link that's still pointing to an absolute path: 

https://github.com/bkimminich/juice-shop/blob/master/frontend/src/app/navbar/navbar.component.ts#L188

There might be more and our test suites won't help us find any broken ones, because it doesn't run the server in a subdirectory. Meaning this is a manual testing exercise that'd need to happen before this gets merged.

**Comment by bkimminich** [comment]
Another candidate? (...and I actually have no time to chase those down...) 

https://github.com/bkimminich/juice-shop/blob/develop/frontend/src/app/order-history/order-history.component.ts#L96

Please do not remove the "🚧" until you are sure to have found _all_ instances where this would cause issues for instances in subdirectories. The FTP folder, promotion video, profile etc. all need to be looked over thoroughly.

**Comment by JamesCullum** [comment]
No, all references with hostServer beforehand work, as it is replaced with `.`

So we need to have tests for this or how do you want to make sure we found everything?

As it is a non-essential feature used by not many people I would fix it as we go.

**Comment by bkimminich** [comment]
I don't think this really warrants effortful test automation, so I'd just rely on you having clicked on every link in the entire application... 😆👍

**Comment by bkimminich** [comment]
The promotion video screen pulls the video for example from another URL, not sure that'll still work in a subdirectory.

**Comment by bkimminich** [comment]
Switched to `master` as it is in preparation for release and more up to date by now that `develop`. In both there were the two merge conflicts in e2e tests. The JWT is trivial to fix, the other one is too messed up for me to fix in GitHub Web UI because tests functions were moved around in the meantime.

**Comment by JamesCullum** [comment]
I've fixed it and am currently running tests.
Rebased to develop - should I rebase again for master?

**Comment by bkimminich** [comment]
If you did to `develop` no more conflicts should be on `master` either when you push! 👍

**Comment by JamesCullum** [comment]
Full changes from commit:

> - Fixed SSTI test, which failed because it didn't trigger the serverside scoring
> - Fixed timing issues in registerSpec and contactSpec, where the XSS didn't work if the browser was too fast
> - Added code way to simulate a proxy environment ina  subfolder. Run via "node test/e2eSubfolder.js"
> - Added e2e test for subfolder. Run via "npm run e2e -- subfolder"
> - Added e2e test for subfolder to travis

Travis appears to be stuck on this PR and doesn't recheck the newest versions

**Comment by bkimminich** [comment]
Can you rebase again, then Travis-CI should realize it has a job to do... 👷

**Comment by JamesCullum** [comment]
As Travis didn't trigger for the last changes or rebases as well, I'm not positive on it. Will try a rebase and otherwise try a new PR.

**Pull request closed without merging**
