### PR TITLE
Revert "Revert "Add user navbar - fix the issues""

### PR DESCRIPTION
**Pull request by bkimminich**

### CODE REVIEW

**Comment by bkimminich** [comment]
@omerlh I think I did it... opened a revert-PR for the revert-PR... 😕

**Comment by omerlh** [comment]
ok thanks. Sorry for all the mess..

**Comment by bkimminich** [comment]
No problem, I messed up the last one by not checking the destination branch properly. Your change will be in v6.1.0 release then. Probably out before 🎄!

**Comment by omerlh** [comment]
Great to hear!

**Pull request merged**
