### PR TITLE
Implementation of Accounting user

### PR DESCRIPTION
**Pull request by agrawalarpit14**
- Addition of an accounting user
- Ability to increase/decrease stock of items(New APIs only accessable by accounting users).
- Ability to increase/decrease price of items(Existing APIs, accessable by all authorized users).
- Addition of AccountingGuard on frontend
- Addition of isAccounting on backend

### CODE REVIEW

**Comment by agrawalarpit14** [comment]
Hi!! @bkimminich @J12934. The implementation of above component can be seen [here](https://drive.google.com/file/d/1mJaVkVNBi6oVaKz9bwPszpHiYyMyQbO-/view?usp=sharing).
Please let me know your feedback.
Thank You!!😁🙂

**Comment by J12934** [comment]
One big open Question for me is, how are JuiceShop users supposed to find the accounting section?
Having a third `score-board` / `administration` type challenge where users have to search through the javascript bundle is something i would not like to see.

I'd suggest adding a accounting navbar entry which gets enabled for accounting users.

**Comment by agrawalarpit14** [comment]
Hi!! @J12934 @bkimminich. Hope you had an awesome flight home.😁
Please let me know your feedback.😁😁
Thank You!!

**Comment by J12934** [comment]
Hey Arpit,
Thank you, the flight home worked out nicely 👌
Will take another look at the PR later

**Comment by bkimminich** [comment]
Please rebase this PR to the latest `gsoc2019` which includes some refactorings - then we should be able to merge. Thanks!

**Comment by bkimminich** [comment]
@J12934 can we merge this change or are there any open points from your side?

**Comment by J12934** [comment]
Sorry forgot to post another review.
I think the PR is ready to get merged.

**Review by J12934 — APPROVED** [review]

**Pull request merged**
