### PR TITLE
User Impersonation Challenge

### PR DESCRIPTION
**Pull request by shoebpate1**

### CODE REVIEW

**Comment by bkimminich** [comment]
@CaptainFreak, please add corresponding test cases to the PR. Thanks!

**Comment by J12934** [comment]
I think the name "Privilege Escalation" is a bit off, as there is no real privilege being escalated here.
Its more of a impersonation, missing access control challenge.

**Comment by J12934** [comment]
Also currently the challenge gets solved when performing the "NoSQL injection 2" Challange, which i don't think should happen...

**Comment by J12934** [comment]
There are still some api and e2e test failing.
Anything i can help you with @CaptainFreak?

**Comment by bkimminich** [comment]
@J12934 or @wurstbrot, you please do the merge into `gsoc-challenges` when you are 👍 with the code, ok? Same for all future PRs to this branch. I'll do the fun part of merging into `gsoc-integration` occasionally.

**Comment by bkimminich** [comment]
Hi @CaptainFreak! Some things you should update before this PR will get merged:
* [x] Rename challenge into `Forged Review`
* [x] Put challenge into category `Broken Access Control` (see https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part1/categories.html) 
* [x] Change difficulty to `3`
* [x] Move e2e test into `noSqlSpec.js` file

**Comment by bkimminich** [comment]
I'll merge your PR and check the tests there. With my fixes upstream it'd be much more effort than necessary to rebase your fork now.

**Pull request merged**
