### PR TITLE
Clean remaining residue when logging-out

### PR DESCRIPTION
**Pull request by cnotin**

### CODE REVIEW

**Comment by bkimminich** [comment]
ℹ️ Unfortunately the Travis-CI pipeline is still unavailable due to missing OSS credits. I've pinged them on the respective support ticket once again, but haven't heard back from them yet. Reviews and merging of open PRs will resume once our CI/CD is back online. Thanks for your contribution and patience! 👍

**Comment by cnotin** [comment]
Looks like a CI bug too!

**Comment by bkimminich** [comment]
Thanks for pinging our new build pipeline! 🥳

**Comment by cnotin** [comment]
Same issue in the e2e tests as in the previous run of my other PR if I recall correctly... I think I saw a commit where you tried to fix it but increasing a timer, isn't it?

**Comment by bkimminich** [comment]
Yep, I thought that might have done it... But never mind, this error is unrelated to your code change, so...

**Pull request merged**
