### PR TITLE
Add Disabled challenge filter button

### PR DESCRIPTION
**Pull request by Scar26**
Added a filter button to show or hide disabled challenges in the scoreboard
Fixes : #1288 

filterdemo

Note : proper checks are in place and the newly added components are only visible in relevant environments. They're visible on localhost in the demo because I manually set the heroku check to true for testing

### CODE REVIEW

**Comment by bkimminich** [comment]
👍 Cool, that looks great! I'd just use only "Show disabled" as button text (for consistency with "Show solved") and maybe add an icon that fits well to it. Also the Info text, if shown only when there are disabled challenges, should read "Some challenges are disabled for security reasons!" and might be in `warn` color?

**Comment by Scar26** [comment]
Done

infobox

**Comment by Scar26** [comment]
I don't understand why the travis build is failing. I don't think I have tampered with anything that might interfere with e2e tests

**Comment by J12934** [comment]
I personally think that a info box, especially in a warning color, which is shown at all time is a bit too "attention grabbing".

Would prefer if this would be like a popover text on the button, only showing when actively hovered over.

**Comment by bkimminich** [comment]
Good point, @J12934 ... I think the link to the documentation is quite good, and we'd loose that in a tooltip. But we could actually move the info box down to the other ones... then it's less "in your face" maybe?

image

**Comment by bkimminich** [comment]
Or we only show the info message at the top when the "Show disabled" button is turned on? By default it'd be off (or not shown at all in local envs), so that would make the message less attention grabbing also?

**Comment by Scar26** [comment]
But wouldn't it make more sense for it to be shown when the show disabled button is off? Because if it's on, you'll be seeing a bunch of challenges mark disabled in the scoreboard anyway.
Putting it at the bottom sounds like a good approach too, how should I go ahead?

Also, any idea why the travis build is failing on e2e tests?

**Comment by bkimminich** [comment]
I restarted the e2e job. It seems to have gotten stuck even before executing anything. Probably a Travis glitch.

**Comment by Scar26** [comment]
Done, the warning is now only visible when the "Show disabled" button is activated

**Comment by bkimminich** [comment]
Okay cool! I'll fix the e2e issues tomorrow and then merge your PR! 👍

**Comment by bkimminich** [comment]
image

**Comment by bkimminich** [comment]
I pushed some changes into a new branch based on your PR. I'll close your PR and merge that branch.

**Pull request closed without merging**
