### PR TITLE
Add bonus points to already existing orders

### PR DESCRIPTION
**Pull request by cnotin**
Before:
image

After:
image

### CODE REVIEW

**Comment by bkimminich** [comment]
Aaah, that's a great fix! 👍 Never noticed that before! Thanks! I'll merge it once the Travis-CI issues are gone!

**Comment by bkimminich** [comment]
ℹ️ Unfortunately the Travis-CI pipeline is still unavailable due to missing OSS credits. I've pinged them on the respective support ticket once again, but haven't heard back from them yet. Reviews and merging of open PRs will resume once our CI/CD is back online. Thanks for your contribution and patience! 👍

**Comment by bkimminich** [comment]
First (if I recall correctly...?) merged PR means you're eligible for our famous sticker pack! If you send me your post address via Twitter DM, Slack or Email I'll make sure you get our little Thank-You maybe even before Christmas!

**Comment by cnotin** [comment]
Not the first PR attempt, but first to land for sure :) Thank you @bkimminich 
I'll send my address via Twitter DM.

**Pull request merged**
