### PR TITLE
Add OSINT challenge - reset scar's password

### PR DESCRIPTION
**Pull request by Scar26**
Fixes: #1358 
the wayback snapshot is available at: https://web.archive.org/web/20200330155712/https://twitter.com/MSC4R

The original tweet has already been deleted from the account https://twitter.com/MSC4R

### CODE REVIEW

**Comment by bkimminich** [comment]
Isn't referencing the twitter handle kind of too easy? No need for Sherlock with this, right? 😅

**Comment by Scar26** [comment]
I mean the prompt doesn't explicitly mention that it's a twitter handle.

`Reset Scar's password via the Forgot Password mechanism with the original answer to his security question. He sometimes goes by MSC4R online.`

What would be a better way to frame this?

**Comment by bkimminich** [comment]
I don't know, maybe make it possible to trace one possible username in one step and then use Sherlock to deduce association to that Twitter account? I've got no experience with Sherlock t.b.h.

**Comment by Scar26** [comment]
How about if we get the account to leave a 0 star review on the shop and a comment on one of the products that says "0 stars for the horrible security. msc4r was here"?

**Comment by bkimminich** [comment]
Yeah, something like that on a review or feedback sounds good!

**Comment by Scar26** [comment]
I've added the review, removed the part from the description where it mentions the twitter handle, and changed the hint to `Maybe you can find some hints across his social media. If only you could find something like an alias...`

Also, looks like Travis is still not working on PRs. This issue seems to have started around the same time the new workflows were added. Could they be causing this somehow?

**Comment by Scar26** [comment]
I guess another way to do it could be that I could change my handle to 5c4r (it isn't taken as of now) and just let people figure out their way from `scar` to `5c4r` themselves?

**Comment by bkimminich** [comment]
Or even meaner, you change it into `5c4r`, wait until it has been archived, then change it back to what it was ... ... okay, maybe that's too much... 🤣

**Comment by Scar26** [comment]
Yeah... renaming the account might make it a little too tough. I guess it would still be solvable though. I might steal this idea for a CTF problem sometime if that's cool  :sweat_smile: 

But which one would be better for this challenge? The review that mentions the twitter handle, or the "guess your way to `5c4r` "?

**Comment by bkimminich** [comment]
If there's some way to make a connection that'd be easy for Sherlock to find but hard to just stumble over by looking, that'd be best.

**Comment by Scar26** [comment]
hm... I'll try to think of a way. Might have to incorporate some other OSINT tool as well, since sherlock is only useful if you already know the username...

I guess a more subtle way to do it would be to have the account leave a review with a bunch of leet words, like: `0 stars f0r th3 h0rr1bl3 s3curi7y j0b` to hint that his handle might also be a leetified version of his name. 

The user could then pass a list of possible alternatives into sherlock since it allows multiple usernames to be searched simultaneously but doesn't automatically do the modification by itself

**Comment by Scar26** [comment]
Nope! Turns out you can't have a handle shorter than 5 characters. I guess it would be better for the sake of the challenge to use a different name for the account.

I was thinking about [Uvogin](https://villains.fandom.com/wiki/Uvogin) , since a slight variation (uv0gin) is available. Could work well with the subtle hint we give out in the review

Also, I've opened an issue on sherlock https://github.com/sherlock-project/sherlock/issues/574
So if they agree, users might be able to fully automate this challenge in the future and it will be relatively simple since this name is quite uncommon as an alias

**Comment by Scar26** [comment]
Got a reply on the sherlock repo. They said they don't want this feature as of now so users will have to do it manually for the time being (though they only have to change O to 0).
The new twitter account is https://twitter.com/uv0gin (added a couple easter eggs to the cover photo so people can easily identify it as being linked to the challenge)
The wayback snapshot: http://web.archive.org/web/20200403193744/https:/twitter.com/uv0gin

Since this is a dummy account there's also no worry of the relevant tweet getting buried

Travis still isn't working for some reason...

**Pull request merged**
