### PR TITLE
Update pt_PT.json

### PR DESCRIPTION
**Pull request by Jpfonseca**
Added translations for new strings .

### CODE REVIEW

**Comment by Jpfonseca** [comment]
@bkimminich if ou can add the label hacktoberfest I would be grateful.

**Comment by bkimminich** [comment]
Thanks! Can you please update your commit message to signify that you agree with our DCO? Go to "Checks > DCO" to check how to do that
Thank you!

**Comment by Jpfonseca** [comment]
Sure,I  did it already. 
Any reason why you have this action enabled ? Just wondering why you don't want signed commits  🤔... It's the fist time I have seen this type of request.

**Comment by bkimminich** [comment]
It's a light weight Contributor License Agreement. Works also when signing with your GitHub primary email, I think...

**Pull request merged**
