### PR TITLE
Keeping frontend modules since the app.js checks whether or not the m…

### PR DESCRIPTION
**Pull request by kodemaan**
This change allows the app to start on the docker container. If there's a reason this was there let me know and I can see if there's a better way to fix this

### CODE REVIEW

**Comment by bkimminich** [comment]
Ah, damn ... this is okay as a workaround. The underlying problem is that on Docker the `npm install` already happened and therefore the `frontend/node_modules` is no longer needed, as it's all packaged into `frontend/dist` already. Same issue would occur for pre-packaged ZIP files I presume... testing that now...

**Comment by bkimminich** [comment]
...and it does occur in the pre-packaged ones as well. Okay, the only sensible solution is to remove the corresponding check for the frontend dependencies being installed. I'll hotfix that asap.

**Comment by kodemaan** [comment]
Alright sounds good I'm pretty sure that's it cause I tried I think 8.4.1
and it worked for the docker image

**Comment by kodemaan** [comment]
I can just close this one and re open if needed since you're going to do the other hotfix

**Comment by bkimminich** [comment]
Thanks for reporting this so quickly! :+1: ... v8.5.1 is on the way through the build pipeline and should fix this issue.

**Comment by kodemaan** [comment]
Glad to help we just went through this at my company and wanted to try it locally when I noticed this :)

**Pull request closed without merging**
