### PR TITLE
Add user navbar - fix the issues

### PR DESCRIPTION
**Pull request by omerlh**
Fix issues from #408:
- [x] contained an unwanted hello: message
- [ ] squeezed the text between logo and application title
- [x] does not update the user after logging in unless you F5 the browser. I was at that same point way back when trying #49

Regarding the squeezed text - this is how it looks like:
screen shot 2017-11-29 at 8 33 18
Did you mean I should make the text look smaller?
I've fixed the update bug - all was required is to emit an event on user login/logout. I tried to add tests for it, but for some reason, it did not work. Do you have any experience with testing event emitter?

### CODE REVIEW

**Comment by omerlh** [comment]
I took a look at code climate issues - I can move this code (most of it is not mine)  into `UserService`. Do you think this make sense?

**Comment by bkimminich** [comment]
No, I never had any event emitters to test so far. How about you put that email into the button-bar, maybe between Logout and the language dropdown? Or make it part of the Logout-button text itself?
 I'm sure that both looks better than in the logo/title section. Don't worry about Codeclimate warning, I have to do some cleanup to do in various places anyway since they changed how the score calculates... 👍

**Comment by omerlh** [comment]
Ok, this is the new look:
screen shot 2017-11-30 at 7 00 12

I think it looks somewhat better. The testing suppose to be simple but it is not working - and I cannot enable debugging. Did you succeed to debug the tests? It is also supposed to be simple, but karma tests are closed before I managed to debug...

**Comment by bkimminich** [comment]
@omerlh Can you reopen another PR please? I didn't see you pointed it to `master` again and did not switch the base to `develop` before merging. Sorry!

**Comment by omerlh** [comment]
Yeah,  sure - sorry for that...

**Pull request merged**
