### PR TITLE
Export profile data feature

### PR DESCRIPTION
**Pull request by aaryan01**
@bkimminich
I've attempted to export the user data (username, email, and orders) in a PDF #660. Let me know what you think. :)
Screenshot 2019-03-19 at 5 04 15 PM
When no order exists
Screenshot 2019-03-19 at 4 57 23 PM
When order(s) exist
Screenshot 2019-03-19 at 5 01 04 PM

Also, if you like the table format, we can implement it in the order summary PDF too.

### CODE REVIEW

**Comment by J12934** [comment]
I think the data export should rather be integrated in the privacy & security page than the dashboard.

It already has a placeholder for the data export feature.

image

**Comment by J12934** [comment]
The linting is currently broken for this pr.
Just in case you don't know, most linting errors can be fixed quite easily:
- For the server: `npx standard --fix`
- For the frontend: `cd frontend && npm run lint -- --fix`

**Comment by aaryan01** [comment]
Hi @J12934 ! I'll update the changes and fix linting in my next commit :+1:  
Thanks

**Comment by bkimminich** [comment]
@aaryan01, I commented #660 on the matter to have ideas not mixed up too much between PR and Issue.

**Comment by bkimminich** [comment]
@aaryan01, do you plan any further updates to implement @J12934's remarks and my own from #660?

**Comment by aaryan01** [comment]
> @aaryan01, do you plan any further updates to implement @J12934's remarks and my own from #660?

Hey @bkimminich ! Apologies for my absence. Yes I'm working on both your suggestions and will be updating my PR shortly. 
Thanks

**Comment by bkimminich** [comment]
Maybe you and @agrawalarpit14 can try to merge #913 with this PR or at least harvest the idea from one into the other?

**Comment by bkimminich** [comment]
Also please check https://github.com/bkimminich/juice-shop/issues/660#issuecomment-475851189 for input on implementation options.

**Comment by agrawalarpit14** [comment]
Hi @bkimminich @aaryan01 If you say, should I go on to merge this PR along with #913 taking the review comments at https://github.com/bkimminich/juice-shop/issues/660#issuecomment-475851189 into account. (I think it will be fairly easy to relate them, as the API calls need to be modified predominantly.)

**Comment by aaryan01** [comment]
Hey @agrawalarpit14 , I've started working on the suggestions, just let me complete the JSON implementation and then you can integrate it with your component and submit the PR?
Thanks!

**Comment by agrawalarpit14** [comment]
> Hey @agrawalarpit14 , I've started working on the suggestions, just let me complete the JSON implementation and then you can integrate it with your component and submit the PR?
> Thanks!

Sure I will be waiting!! Ping me, when u r done.

**Comment by aaryan01** [comment]
Hey @agrawalarpit14 !  I have made the changes, you can create a remote for my fork and fetch branch issue660. Currently, it is integrated in the Profile page. Mail me at aaryanbudhiraja2@gmail.com for any questions.
Thanks!

**Comment by aaryan01** [comment]
Hi @bkimminich , I implemented it for json. Currently, it only displays orders. Working on adding more details.
Screenshot from 2019-04-04 20-33-58

Thanks!

**Comment by bkimminich** [comment]
Merged with #913

**Pull request closed without merging**
